# Generated by Django 2.2.13 on 2020-07-06 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0034_remove_pagecontent_placeholders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='Github Username')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_github_organisationpluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Organisation Name')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='RepositoryPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_github_repositorypluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('name', models.CharField(max_length=255)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangocms_github.OrganisationPluginModel')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='GithubPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_github_githubpluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('credentials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangocms_github.Credentials')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
