# Generated by Django 2.2.13 on 2020-07-06 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0034_remove_pagecontent_placeholders'),
        ('djangocms_github', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_github_organisationpluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Organisation Name')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('html_url', models.URLField(null=True, verbose_name='Github URL')),
                ('blog_url', models.URLField(null=True, verbose_name='Blog URL')),
                ('updated_at', models.DateTimeField(null=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
